### ISSUE TITLE
Scheduling shutdown

### ISSUE THREAD

**Issue by guilhermegazzinelli** [samuelcarreira/electron-shutdown-command#19]
Hi, @samuelcarreira . Firstly, thanks for your work in this lib!!
 
I was trying to schedule a shutdown. Since all of the existent SO permit this function, this could be a an relevant feature for the lib.

Right now I'm just calculating the interval from current time to the shutdown point, but a more direct approach would  be to just pass the time you want to shutdown.  

If you think that this feature is relevant for the project I could help with tests or taking a look and submitting a PR.

Thanks for all.

**Comment by samuelcarreira** [comment]
Hi @guilhermegazzinelli  thank you for your message.
You can only set the schedule timer via parameter (like the example above):

```
/* shutdown after 60 seconds
 */
shutdown.shutdown({
  timerseconds: 60,
  quitapp: true
})
```

Since the purpose of this library is just having a simple wrapper over the shutdown command I don't want to implement more logic (prone to bugs or create a more heavy package).

I think you have two options: 
1. One is to calculate the difference time in seconds and pass the parameter (the command will be run by the OS no matter what) - what you did.
2. Create a simple routine on your app to schedule the shutdown and run the command shutdown immediately (with that you will have plenty of control over the timer functionality and you can choose which time routine you want) 

Regards

**Comment by guilhermegazzinelli** [comment]
Great!!! 

I agree with you about the maintainability!!! 

Thanks for the fast reply!!!

Regards
