### ISSUE TITLE
How about removing electron dependency? (and create new package)

### ISSUE THREAD

**Issue by maxwroc** [samuelcarreira/electron-shutdown-command#2]
Hi 

I was looking for cross platform shutdown npm package and found yours. It seems to be working nice so kudos to you!

The problem is that my project has nothing to do with Electron so I don't want to use it and download unnecessary packages.

What do you think about extracting the core "shutdown/hibernate/sleep/etc" logic into the separate package and publish it as a new npm? I can do it too but I just didn't want to basically take your entire code and publish it as mine package.

Please let me know. Thanks!
Maks

**Comment by samuelcarreira** [comment]
Hi there, this is a very simple code (written in less than one hour), so I think that you can find better alternatives on npmjs.com.
You can create a fork of this project if you want, that is the whole purpose of the Open Source/GitHub community, but if you only want to ignore the electron app that can be easily done because the electron dependency is only used to quit the app.

I created a gist that you can use if you want
https://gist.github.com/samuelcarreira/4deecad5dfa1962e46a300b7367de15f

Regards
