### ISSUE TITLE
Administrator privilegies?

### ISSUE THREAD

**Issue by fabiosoft** [samuelcarreira/electron-shutdown-command#3]
Do i need to run as sudo or administrator to shutdown the computer :(

**Comment by samuelcarreira** [comment]
Hi @fabiosoft if you run this module on Linux or macOs you will need a administrator privileges to run this command. Because I almost only use that module on windows I didn’t write addicional instructions to run on other OS. But if there was a increasing interest on that functionality I can try to prevent that limitation.
You can use setcap command (Linux), just change the path to your app binary 

`sudo setcap CAP_SYS_BOOT=+ep /usr/local/bin/node`
